name = "job-hunter-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "job-hunter-db"
database_id = "b6409864-af25-4f60-bd3f-ad7d36fb1553"
